apiVersion: apps/v1
kind: Deployment
metadata:
 name: argo-demo
spec:
 selector:
   matchLabels:
     run: argo-demo
 replicas: 1
 template:
   metadata:
     labels:
       run: argo-demo
   spec:
     containers:
     - name: argo-demo
       image: us-west1-docker.pkg.dev/nearpeer-394113/dev-microservices-images/argo-demo:55
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 500m
         requests:
           cpu: 100m
